### ISSUE TITLE
FLOPs computation

### ISSUE THREAD

**Issue by juliagusak** [Roll920/ThiNet_Code#2]
Hi @Roll920, 

I am a bit confused with the number of FLOPs (for cnovolutional layers) you provide for VGG-16 (30.94 billion) in  [ThiNet paper](https://arxiv.org/pdf/1707.06342.pdf]) (original model, Table 1). 

In many sources (for example,  [ResNet paper](https://arxiv.org/pdf/1512.03385.pdf) (page 7 top), [Channel pruning paper](https://github.com/yihui-he/channel-pruning) (flops function [here](https://github.com/yihui-he/channel-pruning/blob/master/tools.py)), this [repo](https://github.com/albanie/convnet-burden)) it is stated that VGG-16 has 15.3 billion FLOPs, i.e. two times less ...

Couldn't you tell me,  please, which formula do you use to you compute FLOPs? Thanks a lot!

Best regards,
Julia

**Comment by Roll920** [comment]
Hi @juliagusak ,

There are mainly two methods to calculate the FLOPs. You can refer to Eq. (6) of [AutoPruner paper](https://arxiv.org/pdf/1805.08941.pdf) for more details.

Thank you.

**Comment by juliagusak** [comment]
Thank you for the clarification!
